import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";

export const GENERATED_NOTICE =
  "DO NOT EDIT - generated by `agentkit sync`. Edit the canonical sources in .agents/ instead.";

/** Comment-wrap the generated notice for a given file type. */
export function notice(style: "hash" | "html" | "none"): string {
  switch (style) {
    case "hash":
      return `# ${GENERATED_NOTICE}\n`;
    case "html":
      return `<!-- ${GENERATED_NOTICE} -->\n`;
    case "none":
      return "";
  }
}

export async function exists(p: string): Promise<boolean> {
  try {
    await fs.stat(p);
    return true;
  } catch {
    return false;
  }
}

export async function isDir(p: string): Promise<boolean> {
  try {
    return (await fs.stat(p)).isDirectory();
  } catch {
    return false;
  }
}

export async function readText(p: string): Promise<string> {
  return fs.readFile(p, "utf8");
}

/** Read a file, returning null instead of throwing when it is absent. */
export async function readTextOrNull(p: string): Promise<string | null> {
  try {
    return await fs.readFile(p, "utf8");
  } catch {
    return null;
  }
}

/** Stable content hash used as the manifest baseline. */
export function sha256(data: Buffer | string): string {
  return `sha256-${createHash("sha256").update(data).digest("hex")}`;
}

/** Hash a file's bytes, returning null when it is absent. */
export async function hashFile(p: string): Promise<string | null> {
  try {
    return sha256(await fs.readFile(p));
  } catch {
    return null;
  }
}

/** Every file under `dir`, as sorted paths relative to it. */
export async function listFiles(dir: string, prefix = ""): Promise<string[]> {
  if (!(await isDir(dir))) return [];
  const out: string[] = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const relative = prefix ? path.join(prefix, entry.name) : entry.name;
    if (entry.isDirectory()) {
      out.push(...(await listFiles(path.join(dir, entry.name), relative)));
    } else {
      out.push(relative);
    }
  }
  return out.sort();
}

export async function writeText(p: string, contents: string): Promise<void> {
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, contents, "utf8");
}

/** Mirror `src` onto `dest`, replacing whatever was there. Used for vendor dirs. */
export async function mirrorDir(src: string, dest: string): Promise<void> {
  await fs.rm(dest, { recursive: true, force: true });
  if (!(await isDir(src))) return;
  await fs.cp(src, dest, { recursive: true });
}

/** List files matching a glob, relative paths resolved against `cwd`. */
export async function glob(pattern: string, cwd: string): Promise<string[]> {
  const out: string[] = [];
  for await (const match of fs.glob(pattern, { cwd })) {
    out.push(path.join(cwd, match));
  }
  return out.sort();
}

/** Split YAML-ish frontmatter off the top of a markdown file. */
export function parseFrontmatter(raw: string): {
  frontmatter: Record<string, string>;
  body: string;
} {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(raw);
  if (!match) return { frontmatter: {}, body: raw };

  const frontmatter: Record<string, string> = {};
  for (const line of (match[1] ?? "").split(/\r?\n/)) {
    // Only top-level `key: value` pairs; nested YAML is passed over.
    const kv = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line);
    if (!kv) continue;
    const key = kv[1];
    const value = (kv[2] ?? "").trim().replace(/^["']|["']$/g, "");
    if (key) frontmatter[key] = value;
  }
  return { frontmatter, body: raw.slice(match[0].length) };
}
