import path from "node:path";
import type { PackAction, PackFileState, SeedManifest } from "./types.js";
import { listFiles, readTextOrNull, writeText } from "./fsx.js";

export const MANIFEST_FILE = "agentkit-manifest.json";

const MANIFEST_COMMENT =
  "Generated by `agentkit sync`. Records what each pack-seeded file looked " +
  "like when agentkit wrote it, so pack updates can reach files you have not " +
  "edited. Commit this file; do not edit it by hand.";

/**
 * Decide what to do with one pack file. Pure, so the whole policy is testable
 * without touching a filesystem.
 *
 * The invariant every branch upholds: agentkit only overwrites a file whose
 * current bytes it wrote itself. If the bytes differ from what the manifest
 * recorded, someone edited it and it is theirs.
 */
export function resolvePackFile(
  state: PackFileState,
  reseed = false,
): PackAction {
  const { packHash, localHash, entry } = state;

  // Tombstoned and still gone: honour the deletion unless asked to undo it.
  // If no pack ships it any more the tombstone has nothing left to guard, so
  // the entry is dropped rather than kept forever.
  if (entry?.removed === true && localHash === null) {
    if (packHash === null) return "drop";
    return reseed ? "seed" : "removed";
  }

  // Untracked, or tombstoned and hand-restored - either way agentkit has no
  // baseline for this file, so it may only adopt an exact copy of the pack.
  if (entry === undefined || entry.removed === true) {
    if (packHash === null) return "drop";
    if (localHash === null) return "seed";
    return localHash === packHash ? "adopt" : "unmanaged";
  }

  // The pack stopped shipping it (or the pack was disabled).
  if (packHash === null) return localHash === null ? "drop" : "orphaned";

  if (localHash === null) return "tombstone";

  const unmodified = localHash === entry.hash;
  const packMoved = packHash !== entry.hash;

  if (unmodified) return packMoved ? "update" : "current";
  return packMoved ? "conflict" : "modified";
}

/** Actions that mean sync must write the pack's bytes to disk. */
export function writesFile(action: PackAction): boolean {
  return action === "seed" || action === "update";
}

/** Actions worth printing. `current`, `modified` and `removed` are routine. */
export function isNoteworthy(action: PackAction): boolean {
  return !(action === "current" || action === "modified" || action === "removed" || action === "drop");
}

export async function readManifest(agentsDir: string): Promise<SeedManifest> {
  const raw = await readTextOrNull(path.join(agentsDir, MANIFEST_FILE));
  if (raw === null) return { seeded: {} };
  const parsed = JSON.parse(raw) as Partial<SeedManifest>;
  return { seeded: parsed.seeded ?? {} };
}

export async function writeManifest(
  agentsDir: string,
  manifest: SeedManifest,
): Promise<void> {
  // Sorted so the committed file has a stable diff regardless of pack order.
  const seeded: SeedManifest["seeded"] = {};
  for (const key of Object.keys(manifest.seeded).sort()) {
    const entry = manifest.seeded[key];
    if (entry !== undefined) seeded[key] = entry;
  }
  const body = { $comment: MANIFEST_COMMENT, seeded };
  await writeText(
    path.join(agentsDir, MANIFEST_FILE),
    `${JSON.stringify(body, null, 2)}\n`,
  );
}

/**
 * Files a pack ships, as paths relative to the pack root (`skills/x/SKILL.md`).
 * Only the three known kinds are enumerated, so a stray file in a pack is
 * never copied into a consumer repo by accident.
 */
export async function listPackFiles(packDir: string): Promise<string[]> {
  const out: string[] = [];
  for (const kind of ["skills", "commands"]) {
    for (const relative of await listFiles(path.join(packDir, kind))) {
      out.push(path.join(kind, relative));
    }
  }
  return out.sort();
}
