import path from "node:path";
import type { PackAction, PackFileState, SeedManifest } from "./types.js";
import { listFiles, readTextOrNull, writeText } from "./fsx.js";
import { isOlderThan } from "./version.js";

export const MANIFEST_FILE = "agentkit-manifest.json";

const MANIFEST_COMMENT =
  "Generated by `agentkit sync`. Records what agentkit last wrote - the bytes " +
  "of each pack-seeded file and the version that wrote them, so pack updates " +
  "can reach files you have not edited without an older agentkit undoing them, " +
  "plus the files it copied into each vendor mirror. Commit this file; do not " +
  "edit it by hand.";

/**
 * Decide what to do with one pack file. Pure, so the whole policy is testable
 * without touching a filesystem.
 *
 * The invariant every branch upholds: agentkit only overwrites a file whose
 * current bytes it wrote itself. If the bytes differ from what the manifest
 * recorded, someone edited it and it is theirs.
 *
 * A second invariant makes pack updates directional. "The pack differs from
 * the baseline" has two causes, and they need opposite responses: the pack
 * moved forward, or this agentkit is behind the one that wrote the baseline
 * and is holding an earlier copy of the same file. Comparing versions tells
 * them apart. Without that, an older agentkit overwrites a newer file, records
 * the older hash, and the next developer's newer agentkit puts it back - the
 * two machines trade the file back and forth, one commit at a time.
 */
export function resolvePackFile(
  state: PackFileState,
  reseed = false,
): PackAction {
  const { packHash, localHash, entry } = state;

  // Tombstoned and still gone: honour the deletion unless asked to undo it.
  // If no pack ships it any more the tombstone has nothing left to guard, so
  // the entry is dropped rather than kept forever.
  if (entry?.removed === true && localHash === null) {
    if (packHash === null) return "drop";
    return reseed ? "seed" : "removed";
  }

  // Untracked, or tombstoned and hand-restored - either way agentkit has no
  // baseline for this file, so it may only adopt an exact copy of the pack.
  if (entry === undefined || entry.removed === true) {
    if (packHash === null) return "drop";
    if (localHash === null) return "seed";
    return localHash === packHash ? "adopt" : "unmanaged";
  }

  // The pack stopped shipping it (or the pack was disabled).
  if (packHash === null) return localHash === null ? "drop" : "orphaned";

  if (localHash === null) return "tombstone";

  const unmodified = localHash === entry.hash;

  // The pack agrees with the baseline, so no version can be in question.
  if (packHash === entry.hash) return unmodified ? "current" : "modified";

  // It does not agree. If this build predates the one that wrote the baseline,
  // the disagreement is our own staleness - refuse the file either way.
  if (isOlderThan(state.version, entry.agentkit)) return "stale";

  return unmodified ? "update" : "conflict";
}

/** Actions that mean sync must write the pack's bytes to disk. */
export function writesFile(action: PackAction): boolean {
  return action === "seed" || action === "update";
}

/** Actions worth printing. `current`, `modified` and `removed` are routine. */
export function isNoteworthy(action: PackAction): boolean {
  return !(action === "current" || action === "modified" || action === "removed" || action === "drop");
}

/**
 * Actions that mean this agentkit is too old to be trusted with the repo.
 * They are the one pack state that fails a build rather than queueing work:
 * every other row is a difference agentkit can explain, and this is the row
 * where it cannot see far enough to explain anything.
 */
export function isStale(action: PackAction): boolean {
  return action === "stale";
}

export async function readManifest(agentsDir: string): Promise<SeedManifest> {
  const raw = await readTextOrNull(path.join(agentsDir, MANIFEST_FILE));
  if (raw === null) return { seeded: {}, mirrored: {} };
  const parsed = JSON.parse(raw) as Partial<SeedManifest>;
  return {
    ...(parsed.agentkit === undefined ? {} : { agentkit: parsed.agentkit }),
    seeded: parsed.seeded ?? {},
    mirrored: parsed.mirrored ?? {},
  };
}

export async function writeManifest(
  agentsDir: string,
  manifest: SeedManifest,
): Promise<void> {
  // Sorted so the committed file has a stable diff regardless of pack order.
  const seeded: SeedManifest["seeded"] = {};
  for (const key of Object.keys(manifest.seeded).sort()) {
    const entry = manifest.seeded[key];
    if (entry !== undefined) seeded[key] = entry;
  }
  const mirrored: NonNullable<SeedManifest["mirrored"]> = {};
  for (const key of Object.keys(manifest.mirrored ?? {}).sort()) {
    const files = manifest.mirrored?.[key];
    if (files !== undefined) mirrored[key] = [...files].sort();
  }

  const body = {
    $comment: MANIFEST_COMMENT,
    ...(manifest.agentkit === undefined ? {} : { agentkit: manifest.agentkit }),
    seeded,
    mirrored,
  };
  await writeText(
    path.join(agentsDir, MANIFEST_FILE),
    `${JSON.stringify(body, null, 2)}\n`,
  );
}

/**
 * Files a pack ships, as paths relative to the pack root (`skills/x/SKILL.md`).
 * Only the three known kinds are enumerated, so a stray file in a pack is
 * never copied into a consumer repo by accident.
 */
export async function listPackFiles(packDir: string): Promise<string[]> {
  const out: string[] = [];
  for (const kind of ["skills", "commands"]) {
    for (const relative of await listFiles(path.join(packDir, kind))) {
      out.push(path.join(kind, relative));
    }
  }
  return out.sort();
}
